# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Zexin Fu <zexifu@iis.ee.ethz.ch>

# Run all ci checks
name: ci
on: [push, pull_request]

jobs:
  #####################
  # Vendor Up-to-Date #
  #####################
  # Check that all vendored sources are up-to-date.
  bender-vendor-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check bender vendor up-to-date
        uses: pulp-platform/pulp-actions/bender-vendor-up-to-date@v2.4.1 # update version as needed, not autoupdated
        with:
          bender-version: 0.27.1
